<?php

/**
 * @file
 * Contains commerce_plus.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function commerce_plus_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the commerce_plus module.
    case 'help.page.commerce_plus':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The upgrade of commerce for extension.') . '</p>';
      return $output;

    default:
  }
}
