<?php

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Url;

/**
 * Implements hook_entity_base_field_info_alter().
 */
function user_plus_entity_base_field_info_alter(&$fields, EntityTypeInterface $entity_type) {
  if ($entity_type->id() == 'user' && !empty($fields['name'])) {
    $fields['name']
      ->setDisplayOptions('view', [
        'type' => 'string',
        'weight' => 0,
      ])
      ->setDisplayConfigurable('view', TRUE);
  }
}

/**
 * Implements hook_theme_suggestions_HOOK() for user.
 */
function user_plus_theme_suggestions_user(array $variables) {
  $suggestions = [];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'user__' . $sanitized_view_mode;

  return $suggestions;
}


/**
 * Implements hook_entity_extra_field_info().
 */
function user_plus_entity_extra_field_info() {
  $extra['user']['user']['display']['logout'] = [
    'label' => t('Logout'),
    'weight' => 100,
    'visible' => FALSE,
  ];
  $extra['user']['user']['display']['screen'] = [
    'label' => t('Screen'),
    'weight' => 100,
    'visible' => FALSE,
  ];
  $extra['user']['user']['display']['speech'] = [
    'label' => t('Speech'),
    'weight' => 100,
    'visible' => FALSE,
  ];
  return $extra;
}

/**
 * Implements hook_ENTITY_TYPE_view() for user.
 * @todo need to be polished.
 */
function user_plus_user_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if (\Drupal::currentUser()->id() != 0) {
    if ($display->getComponent('logout')) {
      $build['logout'] = [
        '#type' => 'link',
        '#title' => t('Logout'),
        '#url' => Url::fromRoute('user.logout'),
        '#attributes' => ['class' => ['btn', 'btn-default', 'btn-flat']],
      ];
    }
    if ($display->getComponent('screen')) {
      $build['screen'] = [
        '#type' => 'link',
        '#title' => t('Screen'),
        '#url' => Url::fromRoute('user.logout'),
        '#attributes' => ['class' => ['btn', 'btn-default', 'btn-flat']],
      ];
    }
    if ($display->getComponent('speech')) {
      $build['speech'] = [
        '#type' => 'link',
        '#title' => t('Speech'),
        '#url' => Url::fromRoute('user.logout'),
        '#attributes' => ['class' => ['btn', 'btn-default', 'btn-flat']],
      ];
    }
  }

}

/**
 * Implements hook_preprocess_HOOK() for user.
 */
function user_plus_preprocess_user(&$variables) {
  $variables['attributes']['class'][] = 'user-' . $variables['elements']['#view_mode'];
}
