<?php

/**
 * @file
 * Contains isp_core.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function isp_core_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the isp_core module.
    case 'help.page.isp_core':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The core of isp base.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function isp_core_preprocess_menu__role_menu(&$variables) {
  $icons = [
    'isp_core.admin_isp' => 'fa fa-desktop',
  ];

  _role_menu_set_menu_items_icon($variables['items'], $icons);
}