<?php

/**
 * @file
 * Contains isp_core.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function isp_core_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the isp_core module.
    case 'help.page.isp_core':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The core of isp.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_page_attachments_alter().
 */
function isp_core_page_attachments_alter(array &$attachments) {

}

/**
 * Implements hook_preprocess_HOOK() for menu__role_menu.
 */
function isp_core_preprocess_menu__role_menu(&$variables) {
  $icons = [
//    'eabax_core.implementor.implementation' => 'fa fa-compass',
  ];
  _isp_core_set_menu_items_icon($variables['items'], $icons);
}
function _isp_core_set_menu_items_icon(&$items, $icons) {
  foreach ($items as $key => $item) {
    if (isset($icons[$key])) {
      $items[$key]['icon'] = $icons[$key];
    }

    if (!empty($items['below'])) {
      _isp_core_set_menu_items_icon($item['below'], $icons);
    }
  }
}