<?php

/**
 * @file
 * Contains ip_plus.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ip_plus_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ip_plus module.
    case 'help.page.ip_plus':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The IP Plus module.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function ip_plus_theme() {
  $theme = [];
  $theme['ip'] = [
    'render element' => 'elements',
    'file' => 'ip.page.inc',
    'template' => 'ip',
  ];
  $theme['ip_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'ip.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function ip_plus_theme_suggestions_ip(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#ip'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'ip__' . $sanitized_view_mode;
  $suggestions[] = 'ip__' . $entity->bundle();
  $suggestions[] = 'ip__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'ip__' . $entity->id();
  $suggestions[] = 'ip__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
