<?php

/**
 * @file
 * Contains message_plus.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function message_plus_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the message_plus module.
    case 'help.page.message_plus':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The message plus for contrib module message.') . '</p>';
      return $output;

    default:
  }
}
