#config_rewrite: 'replace'
langcode: en
status: true
dependencies:
  config:
    - commerce_product.commerce_product_variation_type.default
    - core.entity_view_mode.commerce_product_variation.summary
    - field.field.commerce_product_variation.default.attribute_class
    - field.field.commerce_product_variation.default.billing_schedule
    - field.field.commerce_product_variation.default.field_bandwidth
    - field.field.commerce_product_variation.default.field_cpu
    - field.field.commerce_product_variation.default.field_ram
    - field.field.commerce_product_variation.default.field_storage
    - field.field.commerce_product_variation.default.subscription_type
  enforced:
    module:
      - commerce_checkout
  module:
    - commerce_price
    - ds
id: commerce_product_variation.default.summary
targetEntityType: commerce_product_variation
bundle: default
mode: summary
content:
  field_bandwidth:
    type: entity_reference_label
    weight: 5
    region: content
    label: inline
    settings:
      link: false
    third_party_settings: {  }
  field_cpu:
    type: entity_reference_label
    weight: 2
    region: content
    label: inline
    settings:
      link: false
    third_party_settings: {  }
  field_ram:
    type: entity_reference_label
    weight: 3
    region: content
    label: inline
    settings:
      link: false
    third_party_settings: {  }
  field_storage:
    type: entity_reference_label
    weight: 4
    region: content
    label: inline
    settings:
      link: false
    third_party_settings:
      ds:
        ds_limit: ''
  list_price:
    label: above
    type: commerce_price_default
    weight: 1
    region: content
    settings:
      strip_trailing_zeroes: false
      currency_display: symbol
    third_party_settings: {  }
  title:
    label: hidden
    type: string
    weight: 0
    settings:
      link_to_entity: false
    third_party_settings: {  }
    region: content
hidden:
  attribute_class: true
  billing_schedule: true
  langcode: true
  price: true
  product_id: true
  sku: true
  subscription_type: true
