config_rewrite: 'replace'
langcode: en
status: true
dependencies:
  config:
    - commerce_product.commerce_product_variation_type.default
    - field.field.commerce_product_variation.default.attribute_class
    - field.field.commerce_product_variation.default.billing_schedule
    - field.field.commerce_product_variation.default.field_bandwidth
    - field.field.commerce_product_variation.default.field_cpu
    - field.field.commerce_product_variation.default.field_ram
    - field.field.commerce_product_variation.default.field_storage
    - field.field.commerce_product_variation.default.subscription_type
  module:
    - commerce
    - commerce_price
id: commerce_product_variation.default.default
targetEntityType: commerce_product_variation
bundle: default
mode: default
content:
  attribute_class:
    type: options_select
    weight: 4
    settings: {  }
    third_party_settings: {  }
    region: content
  billing_schedule:
    type: options_select
    weight: 11
    settings: {  }
    third_party_settings: {  }
    region: content
  field_bandwidth:
    type: options_select
    weight: 10
    region: content
    settings: {  }
    third_party_settings: {  }
  field_cpu:
    type: options_select
    weight: 7
    region: content
    settings: {  }
    third_party_settings: {  }
  field_ram:
    type: options_select
    weight: 8
    region: content
    settings: {  }
    third_party_settings: {  }
  field_storage:
    type: options_select
    weight: 9
    region: content
    settings: {  }
    third_party_settings: {  }
  langcode:
    type: language_select
    weight: 5
    region: content
    settings:
      include_locked: true
    third_party_settings: {  }
  list_price:
    type: commerce_list_price
    weight: 1
    region: content
    settings: {  }
    third_party_settings: {  }
  price:
    type: commerce_price_default
    weight: 2
    settings: {  }
    third_party_settings: {  }
    region: content
  sku:
    type: string_textfield
    weight: 0
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
    region: content
  status:
    type: boolean_checkbox
    weight: 6
    settings:
      display_label: true
    third_party_settings: {  }
    region: content
  subscription_type:
    type: commerce_plugin_select
    weight: 3
    settings: {  }
    third_party_settings: {  }
    region: content
hidden:
  created: true
  uid: true
