<?php

/**
 * @file
 * Contains isp_room.module.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function isp_room_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the isp_room module.
    case 'help.page.isp_room':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The server of room.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_base_field_info().
 */
function isp_room_entity_base_field_info(EntityTypeInterface $entity_type) {
  if ($entity_type->id() == 'isp_server') {
    $fields = [];
    $fields['room'] = BaseFieldDefinition::create('entity_reference')
      ->setLabel(t('Room'))
      ->setRequired(TRUE)
      ->setSetting('target_type', 'isp_room')
      ->setDisplayOptions('view', [
        'type' => 'entity_reference_label',
        'weight' => 0,
      ])
      ->setDisplayOptions('form', [
        'type' => 'options_select',
        'weight' => 0,
      ])
      ->setDisplayConfigurable('form', TRUE)
      ->setDisplayConfigurable('view', TRUE);

    return $fields;
  }
}

/**
 * Implements hook_theme().
 */
function isp_room_theme() {
  $theme = [];
  $theme['isp_room'] = [
    'render element' => 'elements',
    'file' => 'isp_room.page.inc',
    'template' => 'isp_room',
  ];
  $theme['isp_room_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'isp_room.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function isp_room_theme_suggestions_isp_room(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#isp_room'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'isp_room__' . $sanitized_view_mode;
  $suggestions[] = 'isp_room__' . $entity->bundle();
  $suggestions[] = 'isp_room__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'isp_room__' . $entity->id();
  $suggestions[] = 'isp_room__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}

