isp_server.type.*:
  type: config_entity
  label: 'Server type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    workflow:
      type: string
      label: 'Workflow'
    uuid:
      type: string
