# Schema for the configuration files of the server module.

server.settings:
  type: config_object
  label: 'Server settings'
  mapping:
    master_ip:
      type: string
      label: 'The master ip for unique for all server.'