<?php

/**
 * @file
 * Contains isp_room.module.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function isp_room_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the isp_room module.
    case 'help.page.isp_room':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The server of room.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_base_field_info().
 */
function isp_room_entity_base_field_info(EntityTypeInterface $entity_type) {
  if ($entity_type->id() == 'isp_server') {
    $fields = [];
    $fields['room'] = BaseFieldDefinition::create('entity_reference')
      ->setLabel(t('Room'))
      ->setSetting('target_type', 'isp_room');

    return $fields;
  }
}
