<?php

/**
 * @file
 * Contains property.module.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function property_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the property module.
    case 'help.page.property':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The property for isp, server, cabinet, and so on.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implement hook_entity_base_field_info() for ip.
 */
function property_entity_base_field_info(EntityTypeInterface $entity_type) {
  if ($entity_type->id() == 'ip') {
    $fields = [];
    $fields['property'] = BaseFieldDefinition::create('entity_reference')
      ->setLabel(t('Property'))
      ->setDescription(t('Property right'))
      ->setSetting('target_type', 'property')
      ->setDefaultValue(1)
      ->setDisplayOptions('view', [
        'type' => 'entity_reference_label',
        'weight' => -3,
      ])
      ->setDisplayOptions('form', [
        'type' => 'entity_reference_autocomplete',
        'weight' => 6,
        'settings' => [
          'match_operator' => 'CONTAINS',
          'size' => '60',
          'placeholder' => '',
        ],
      ])
      ->setDisplayConfigurable('form', TRUE)
      ->setDisplayConfigurable('view', TRUE);
    
    return $fields;
  }
  
  if ($entity_type->id() == 'server') {
    $fields = [];
    $fields['property'] = BaseFieldDefinition::create('entity_reference')
      ->setLabel(t('Property'))
      ->setDescription(t('Property right'))
      ->setSetting('target_type', 'property')
      ->setDefaultValue(1)
      ->setDisplayOptions('view', [
        'type' => 'entity_reference_label',
        'weight' => -3,
      ])
      ->setDisplayOptions('form', [
        'type' => 'entity_reference_autocomplete',
        'weight' => 6,
        'settings' => [
          'match_operator' => 'CONTAINS',
          'size' => '60',
          'placeholder' => '',
        ],
      ])
      ->setDisplayConfigurable('form', TRUE)
      ->setDisplayConfigurable('view', TRUE);
    
    return $fields;
  }
}
